// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: helloworld/helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAttestationManagerService_UpdateNodeAttestationStatus_FullMethodName = "/AttestationManager.NodeAttestationManagerService/UpdateNodeAttestationStatus"
)

// NodeAttestationManagerServiceClient is the client API for NodeAttestationManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAttestationManagerServiceClient interface {
	// NodeAttestationManagerService is called from edge node to set the attestaion status
	UpdateNodeAttestationStatus(ctx context.Context, in *UpdateNodeAttestStatusRequest, opts ...grpc.CallOption) (*UpdateNodeAttestStatusResponse, error)
}

type nodeAttestationManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAttestationManagerServiceClient(cc grpc.ClientConnInterface) NodeAttestationManagerServiceClient {
	return &nodeAttestationManagerServiceClient{cc}
}

func (c *nodeAttestationManagerServiceClient) UpdateNodeAttestationStatus(ctx context.Context, in *UpdateNodeAttestStatusRequest, opts ...grpc.CallOption) (*UpdateNodeAttestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeAttestStatusResponse)
	err := c.cc.Invoke(ctx, NodeAttestationManagerService_UpdateNodeAttestationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAttestationManagerServiceServer is the server API for NodeAttestationManagerService service.
// All implementations must embed UnimplementedNodeAttestationManagerServiceServer
// for forward compatibility.
type NodeAttestationManagerServiceServer interface {
	// NodeAttestationManagerService is called from edge node to set the attestaion status
	UpdateNodeAttestationStatus(context.Context, *UpdateNodeAttestStatusRequest) (*UpdateNodeAttestStatusResponse, error)
	mustEmbedUnimplementedNodeAttestationManagerServiceServer()
}

// UnimplementedNodeAttestationManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAttestationManagerServiceServer struct{}

func (UnimplementedNodeAttestationManagerServiceServer) UpdateNodeAttestationStatus(context.Context, *UpdateNodeAttestStatusRequest) (*UpdateNodeAttestStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeAttestationStatus not implemented")
}
func (UnimplementedNodeAttestationManagerServiceServer) mustEmbedUnimplementedNodeAttestationManagerServiceServer() {
}
func (UnimplementedNodeAttestationManagerServiceServer) testEmbeddedByValue() {}

// UnsafeNodeAttestationManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAttestationManagerServiceServer will
// result in compilation errors.
type UnsafeNodeAttestationManagerServiceServer interface {
	mustEmbedUnimplementedNodeAttestationManagerServiceServer()
}

func RegisterNodeAttestationManagerServiceServer(s grpc.ServiceRegistrar, srv NodeAttestationManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeAttestationManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAttestationManagerService_ServiceDesc, srv)
}

func _NodeAttestationManagerService_UpdateNodeAttestationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeAttestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAttestationManagerServiceServer).UpdateNodeAttestationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAttestationManagerService_UpdateNodeAttestationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAttestationManagerServiceServer).UpdateNodeAttestationStatus(ctx, req.(*UpdateNodeAttestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAttestationManagerService_ServiceDesc is the grpc.ServiceDesc for NodeAttestationManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAttestationManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AttestationManager.NodeAttestationManagerService",
	HandlerType: (*NodeAttestationManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateNodeAttestationStatus",
			Handler:    _NodeAttestationManagerService_UpdateNodeAttestationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}
